/*
  INSTRUCTIONS:

  FOR BEST EXPERIENCE SET YOUR MONITOR RESOLUTION TO 800X800
  DUE TO GRAPHIC/ASTHETIC/LOGIC LIMITATIONS THE GAME PLAYS IN A 300X300 WINDOW(the window it would of been played on on a real gameboy)
  SO IF YOU SET YOUR MONITOR TO 800X800 THE VIEWING EXPERIENCE IS MUCH BETTER THEN AT 1080P
  IT WOULD OF BEEN MUCH HARDER TO CODE IT TO BE LARGER ON A LOGIC LEVEL AND WOULDNT OF ACTUALLY LOOKED BETTER
  SINCE THE PNGS ARE 300X300 ANYWAY SO BLOWING THEM UP LARGER WOULDNT MAKE IT LOOK BETTER.

  1) To start SPAM "A"
  - (callback to SUPERSTITION that if you spam A while pokeball rolls back and forth
    there is a higher chance to capture)
  2) WASD: move w up a left s down d right
  3) q to attack

*/
